### ISSUE TITLE
Other exynos5420 tablets

### ISSUE THREAD

**Issue by AlperHuda** [exynos5420/manifests#4]
Hi, i know you are just working for SM-T900 but Lineage 16.0 or 17.1 will it happen for other exynos 5420 devices like SM-P600?
Thanks.

**Comment by thompatry** [comment]
Yes. We are working on bringing up all the devices to the latest.

**Comment by AlperHuda** [comment]
Hi sorry for disturbing, i know you are working for stable lineageos trees i really respect that .i dont want to ask eta but can you say possible time (for example nearly 1 month).Thanks for your team's work
Lastly i found these xda topic did you see that:
https://forum.xda-developers.com/galaxy-note-pro-12/development/rom-lineage-17-1-android-10-q-20200824-t4152395
